[Icon Theme]
Name=glabels-flat-dark
Comment=gLabels flat icon theme (dark)
Directories=16x16/actions,16x16/apps,22x22/actions,22x22/apps,24x24/actions,24x24/apps,32x32/actions,32x32/apps,48x48/actions,48x48/apps,128x128/apps,scalable/apps


[16x16/actions]
Size=16
Type=Fixed
Context=Actions

[16x16/apps]
Size=16
Type=Fixed
Context=Applications

[22x22/actions]
Size=22
Type=Fixed
Context=Actions

[22x22/apps]
Size=22
Type=Fixed
Context=Applications

[24x24/actions]
Size=24
Type=Fixed
Context=Actions

[24x24/apps]
Size=24
Type=Fixed
Context=Applications

[32x32/actions]
Size=32
Type=Fixed
Context=Actions

[32x32/apps]
Size=32
Type=Fixed
Context=Applications

[48x48/actions]
Size=48
Type=Fixed
Context=Actions

[48x48/apps]
Size=48
Type=Fixed
Context=Applications

[128x128/apps]
Size=128
Type=Fixed
Context=Actions

[scalable/apps]
Type=Scalable
Context=Applications
